sudo: required
services:
  - docker

before_install:
  - docker build -t ajpeng/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajpeng/react-test npm test

after_sucess:
  - docker build -t ajpeng/multi-client ./client
  - docker build -t ajpeng/multi-nginx ./nginx
  - docker build -t ajpeng/multi-server ./server
  - docker build -t ajpeng/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them into docker hub
  - docker push ajpeng/multi-client
  - docker push ajpeng/multi-nginx
  - docker push ajpeng/multi-server
  - docker push ajpeng/multi-worker

